server:
  port: "${PORT}"
logging:
  level:
    root: "INFO"
    com.crediya.applications: "DEBUG"
    org.springframework.security: "DEBUG"
spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: "crediya-applications"
    version: "1.0.0"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  liquibase:
    enabled: true
    url: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
    user: "${DB_USER}"
    password: "${DB_PASSWORD}"
    change-log: "classpath:/db/changelog/db.changelog-master.yaml"
  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: "${JWT_SECRET_KEY}"
adapters:
  r2dbc:
    host: "${DB_HOST}"
    port: "${DB_PORT}"
    database: "${DB_NAME}"
    schema: "public"
    username: "${DB_USER}"
    password: "${DB_PASSWORD}"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
  health:
    circuitbreakers:
      enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
adapter:
  restconsumer:
    crediya-auth:
      url: "http://${CREDIYA_AUTH_HOST}:${CREDIYA_AUTH_PORT}"
      timeout: 5000
      path:
        getUserByIdentityCardNumber: "/api/v1/users/{identity_card_number}"
        getUsers: "/api/v1/users"
  sqs:
    region: "${AWS_SQS_CREDIYA_SQS_REGION}"
    queueUrl: "${AWS_SQS_CREDIYA_SQS_QUEUE_URL}"
    endpoint: "http://localhost:4566"
resilience4j:
  circuitbreaker:
    instances:
      testGet:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
      testPost:
        registerHealthIndicator: true
        failureRateThreshold: 50
        slowCallRateThreshold: 50
        slowCallDurationThreshold: "2s"
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: "10s"
route:
  path:
    startApplication: "/api/v1/applications"
    getApplications: "/api/v1/applications"
    updateApplication: "/api/v1/applications/{application_id}"
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://localhost:4566/000000000000/sample"
    waitTimeSeconds: 20
    maxNumberOfMessages: 10
    visibilityTimeoutSeconds: 10
    numberOfThreads: 1
